# Generated by Django 4.1.7 on 2023-03-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shooping_cart', '0003_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
